#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# Authors: Quinn Storm (quinn@beryl-project.org)
#          Patrick Niklaus (marex@opencompositing.org)
# Copyright (C) 2007 Quinn Storm

import pygtk
pygtk.require('2.0')
import gtk

import locale
import gettext
locale.setlocale(locale.LC_ALL, "")
gettext.bindtextdomain("ccsm", DataDir + "/locale")
gettext.textdomain("ccsm")
_ = gettext.gettext

try:
	import sexy
	has_sexy = True
except ImportError:
	print _("Warning: No sexy-python package found.")
	has_sexy = False

if gtk.pygtk_version < (2,10,0):
    print _("PyGtk 2.10.0 or later required")
    raise SystemExit

import compizconfig
ccs = compizconfig
import ccm

screens = ccm.getScreens()
context = ccs.Context(screens)
mainWin = ccm.MainWin(context)
mainWin.show_all()

gtk.main()
